// import type { HttpContext } from '@adonisjs/core/http'

import JSONProcessor from '../processors/JSONProcessor.js'
import ClaimsController from '#controllers/claims_controller'

export default class TestsController {
  claim = new ClaimsController()
  async post() {
    const data = `
    <?xml version="1.0" encoding="UTF-8"?>
<Claim xmlns="http://zieto.co.za/claim/zmf">
  <Response>
    <TransactionResponse>
      <Type>CR</Type>
      <Number>09132024110618</Number>
      <DateTime>20240913130650</DateTime>
    </TransactionResponse>
    <Member>
      <MedicalSchemeNumber>11985051</MedicalSchemeNumber>
      <MedicalSchemeName>CIMUZW</MedicalSchemeName>
    </Member>
    <Patient>
      <DependantCode>00</DependantCode>
      <NewBornIndicator>N</NewBornIndicator>
      <Personal>
        <Title>MR</Title>
        <Surname>MASIMBA</Surname>
        <FirstName>FINE</FirstName>
        <Initials>F</Initials>
        <Gender>M</Gender>
        <DateOfBirth>19860120</DateOfBirth>
      </Personal>
    </Patient>
    <ClaimHeaderResponse>
      <ResponseCode>P</ResponseCode>
      <Message>
        <Type>I</Type>
        <Code>130</Code>
        <Description>Biometric matched to beneficiary</Description>
      </Message>
      <TotalValues>
        <GrossAmount>65435</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>65435</PatientPayAmount>
      </TotalValues>
    </ClaimHeaderResponse>
    <ServiceResponse>
      <Number>1</Number>
      <Identifier>2551</Identifier>
      <SubTotalValues>
        <GrossAmount>0</GrossAmount>
        <NettAmount>0</NettAmount>
        <PatientPayAmount>0</PatientPayAmount>
      </SubTotalValues>
      <ConsumableResponse>
        <Number>1</Number>
        <CodeSet>NSC</CodeSet>
        <Code>20647</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017488</ReferenceNumber>
        <AuthorisationNumber>26907881</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>840</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>840</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>2</Number>
        <CodeSet>NSC</CodeSet>
        <Code>2457</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017489</ReferenceNumber>
        <AuthorisationNumber>26907883</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>294</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>294</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>3</Number>
        <CodeSet>NSC</CodeSet>
        <Code>3076</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017490</ReferenceNumber>
        <AuthorisationNumber>26907885</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>189</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>189</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <TotalValues>
        <GrossAmount>1323</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>1323</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
    <ServiceResponse>
      <Number>2</Number>
      <Identifier>2561</Identifier>
      <SubTotalValues>
        <GrossAmount>0</GrossAmount>
        <NettAmount>0</NettAmount>
        <PatientPayAmount>0</PatientPayAmount>
      </SubTotalValues>
      <ConsumableResponse>
        <Number>1</Number>
        <CodeSet>NSC</CodeSet>
        <Code>608690</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017491</ReferenceNumber>
        <AuthorisationNumber>26907886</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>7</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>7</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>2</Number>
        <CodeSet>NSC</CodeSet>
        <Code>610110</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017492</ReferenceNumber>
        <AuthorisationNumber>26907887</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>50</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>50</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <TotalValues>
        <GrossAmount>57</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>57</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
    <ServiceResponse>
      <Number>3</Number>
      <BenefitCode>UNK</BenefitCode>
      <Identifier>2075</Identifier>
      <SubTotalValues>
        <GrossAmount>7789</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>7789</PatientPayAmount>
      </SubTotalValues>
      <Message>
        <Type>W</Type>
        <Code>3002</Code>
        <Description>CLAIM UNDER REVIEW</Description>
      </Message>
      <TotalValues>
        <GrossAmount>7789</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>7789</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
    <ServiceResponse>
      <Number>4</Number>
      <Identifier>2559</Identifier>
      <SubTotalValues>
        <GrossAmount>0</GrossAmount>
        <NettAmount>0</NettAmount>
        <PatientPayAmount>0</PatientPayAmount>
      </SubTotalValues>
      <ConsumableResponse>
        <Number>1</Number>
        <CodeSet>NSC</CodeSet>
        <Code>2367</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017494</ReferenceNumber>
        <AuthorisationNumber>26907889</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>1000</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>1000</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>2</Number>
        <CodeSet>NSC</CodeSet>
        <Code>10240</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017495</ReferenceNumber>
        <AuthorisationNumber>26907890</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>300</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>300</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>3</Number>
        <CodeSet>NSC</CodeSet>
        <Code>2309</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017496</ReferenceNumber>
        <AuthorisationNumber>26907891</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>400</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>400</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>4</Number>
        <CodeSet>NSC</CodeSet>
        <Code>20263</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017497</ReferenceNumber>
        <AuthorisationNumber>26907892</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>800</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>800</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>5</Number>
        <CodeSet>NSC</CodeSet>
        <Code>20305</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017498</ReferenceNumber>
        <AuthorisationNumber>26907893</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>300</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>300</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>6</Number>
        <CodeSet>NSC</CodeSet>
        <Code>4664</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017499</ReferenceNumber>
        <AuthorisationNumber>26907894</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>800</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>800</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>7</Number>
        <CodeSet>NSC</CodeSet>
        <Code>13058</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017500</ReferenceNumber>
        <AuthorisationNumber>26907895</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>400</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>400</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>8</Number>
        <CodeSet>NSC</CodeSet>
        <Code>2484</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017501</ReferenceNumber>
        <AuthorisationNumber>26907896</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>500</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>500</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <TotalValues>
        <GrossAmount>4500</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>4500</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
    <ServiceResponse>
      <Number>5</Number>
      <Identifier>2569</Identifier>
      <SubTotalValues>
        <GrossAmount>0</GrossAmount>
        <NettAmount>0</NettAmount>
        <PatientPayAmount>0</PatientPayAmount>
      </SubTotalValues>
      <ConsumableResponse>
        <Number>1</Number>
        <CodeSet>NSC</CodeSet>
        <Code>4017</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017502</ReferenceNumber>
        <AuthorisationNumber>26907897</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>800</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>800</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>2</Number>
        <CodeSet>NSC</CodeSet>
        <Code>610235</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017503</ReferenceNumber>
        <AuthorisationNumber>26907898</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>100</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>100</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>3</Number>
        <CodeSet>NSC</CodeSet>
        <Code>35018</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017504</ReferenceNumber>
        <AuthorisationNumber>26907899</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>1500</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>1500</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>4</Number>
        <CodeSet>NSC</CodeSet>
        <Code>605280</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017505</ReferenceNumber>
        <AuthorisationNumber>26907900</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>60</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>60</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>5</Number>
        <CodeSet>NSC</CodeSet>
        <Code>605290</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017506</ReferenceNumber>
        <AuthorisationNumber>26907901</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>60</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>60</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>6</Number>
        <CodeSet>NSC</CodeSet>
        <Code>606190</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017507</ReferenceNumber>
        <AuthorisationNumber>26907902</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>155</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>155</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>7</Number>
        <CodeSet>NSC</CodeSet>
        <Code>605275</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017508</ReferenceNumber>
        <AuthorisationNumber>26907903</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>50</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>50</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>8</Number>
        <CodeSet>NSC</CodeSet>
        <Code>607805</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017509</ReferenceNumber>
        <AuthorisationNumber>26907904</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>40</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>40</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>9</Number>
        <CodeSet>NSC</CodeSet>
        <Code>607815</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017510</ReferenceNumber>
        <AuthorisationNumber>26907905</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>40</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>40</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>10</Number>
        <CodeSet>NSC</CodeSet>
        <Code>607810</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017511</ReferenceNumber>
        <AuthorisationNumber>26907906</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>40</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>40</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>11</Number>
        <CodeSet>NSC</CodeSet>
        <Code>608390</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017512</ReferenceNumber>
        <AuthorisationNumber>26907907</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>1500</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>1500</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>12</Number>
        <CodeSet>NSC</CodeSet>
        <Code>604580</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017514</ReferenceNumber>
        <AuthorisationNumber>26907908</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>750</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>750</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>13</Number>
        <CodeSet>NSC</CodeSet>
        <Code>610245</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017516</ReferenceNumber>
        <AuthorisationNumber>26907909</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>100</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>100</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>14</Number>
        <CodeSet>NSC</CodeSet>
        <Code>607030</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017518</ReferenceNumber>
        <AuthorisationNumber>26907910</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>R</Type>
          <Code>6002</Code>
          <Description>SCHEME RULES APPLIED</Description>
        </Message>
        <TotalValues>
          <GrossAmount>1200</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>1200</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>15</Number>
        <CodeSet>NSC</CodeSet>
        <Code>611060</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017520</ReferenceNumber>
        <AuthorisationNumber>26907911</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>R</Type>
          <Code>15</Code>
          <Description>NAPPI CODE INCORRECT/LACKING - PLEASE RECTIFY</Description>
        </Message>
        <TotalValues>
          <GrossAmount>1000</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>1000</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>16</Number>
        <CodeSet>NSC</CodeSet>
        <Code>35081</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017521</ReferenceNumber>
        <AuthorisationNumber>26907912</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>1000</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>1000</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>17</Number>
        <CodeSet>NSC</CodeSet>
        <Code>4376</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017522</ReferenceNumber>
        <AuthorisationNumber>26907913</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>R</Type>
          <Code>15</Code>
          <Description>NAPPI CODE INCORRECT/LACKING - PLEASE RECTIFY</Description>
        </Message>
        <TotalValues>
          <GrossAmount>1500</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>1500</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>18</Number>
        <CodeSet>NSC</CodeSet>
        <Code>607370</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017523</ReferenceNumber>
        <AuthorisationNumber>26907914</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>100</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>100</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>19</Number>
        <CodeSet>NSC</CodeSet>
        <Code>13290</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017524</ReferenceNumber>
        <AuthorisationNumber>26907915</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>200</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>200</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>20</Number>
        <CodeSet>NSC</CodeSet>
        <Code>609850</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017525</ReferenceNumber>
        <AuthorisationNumber>26907916</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>R</Type>
          <Code>6002</Code>
          <Description>SCHEME RULES APPLIED</Description>
        </Message>
        <TotalValues>
          <GrossAmount>150</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>150</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>21</Number>
        <CodeSet>NSC</CodeSet>
        <Code>LUBR680PP</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017526</ReferenceNumber>
        <AuthorisationNumber>26907917</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>R</Type>
          <Code>15</Code>
          <Description>NAPPI CODE INCORRECT/LACKING - PLEASE RECTIFY</Description>
        </Message>
        <TotalValues>
          <GrossAmount>130</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>130</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>22</Number>
        <CodeSet>NSC</CodeSet>
        <Code>608900</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017527</ReferenceNumber>
        <AuthorisationNumber>26907918</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>200</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>200</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>23</Number>
        <CodeSet>NSC</CodeSet>
        <Code>609890</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017528</ReferenceNumber>
        <AuthorisationNumber>26907919</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>48</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>48</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>24</Number>
        <CodeSet>NSC</CodeSet>
        <Code>611146</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017529</ReferenceNumber>
        <AuthorisationNumber>26907920</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>R</Type>
          <Code>15</Code>
          <Description>NAPPI CODE INCORRECT/LACKING - PLEASE RECTIFY</Description>
        </Message>
        <TotalValues>
          <GrossAmount>2000</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>2000</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>25</Number>
        <CodeSet>NSC</CodeSet>
        <Code>607830</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017530</ReferenceNumber>
        <AuthorisationNumber>26907921</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>100</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>100</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>26</Number>
        <CodeSet>NSC</CodeSet>
        <Code>110320</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017531</ReferenceNumber>
        <AuthorisationNumber>26907922</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>R</Type>
          <Code>15</Code>
          <Description>NAPPI CODE INCORRECT/LACKING - PLEASE RECTIFY</Description>
        </Message>
        <TotalValues>
          <GrossAmount>1000</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>1000</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>27</Number>
        <CodeSet>NSC</CodeSet>
        <Code>605320</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017532</ReferenceNumber>
        <AuthorisationNumber>26907923</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>200</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>200</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>28</Number>
        <CodeSet>NSC</CodeSet>
        <Code>605330</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017533</ReferenceNumber>
        <AuthorisationNumber>26907924</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>100</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>100</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <ConsumableResponse>
        <Number>29</Number>
        <CodeSet>NSC</CodeSet>
        <Code>605335</Code>
        <Quantity>0</Quantity>
        <BenefitCode>UNK</BenefitCode>
        <ReferenceNumber>16017534</ReferenceNumber>
        <AuthorisationNumber>26907925</AuthorisationNumber>
        <WhomToPay>P</WhomToPay>
        <Identifier>793450</Identifier>
        <Message>
          <Type>W</Type>
          <Code>3002</Code>
          <Description>CLAIM UNDER REVIEW</Description>
        </Message>
        <TotalValues>
          <GrossAmount>200</GrossAmount>
          <NettAmount>0</NettAmount>
          <LevyAmount>0</LevyAmount>
          <PatientPayAmount>200</PatientPayAmount>
        </TotalValues>
      </ConsumableResponse>
      <TotalValues>
        <GrossAmount>14323</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>14323</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
    <ServiceResponse>
      <Number>6</Number>
      <BenefitCode>UNK</BenefitCode>
      <Identifier>2303</Identifier>
      <SubTotalValues>
        <GrossAmount>16043</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>16043</PatientPayAmount>
      </SubTotalValues>
      <Message>
        <Type>W</Type>
        <Code>3002</Code>
        <Description>CLAIM UNDER REVIEW</Description>
      </Message>
      <TotalValues>
        <GrossAmount>16043</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>16043</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
    <ServiceResponse>
      <Number>7</Number>
      <BenefitCode>UNK</BenefitCode>
      <Identifier>2316</Identifier>
      <SubTotalValues>
        <GrossAmount>2000</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>2000</PatientPayAmount>
      </SubTotalValues>
      <Message>
        <Type>W</Type>
        <Code>3002</Code>
        <Description>CLAIM UNDER REVIEW</Description>
      </Message>
      <TotalValues>
        <GrossAmount>2000</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>2000</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
    <ServiceResponse>
      <Number>8</Number>
      <BenefitCode>UNK</BenefitCode>
      <Identifier>2306</Identifier>
      <SubTotalValues>
        <GrossAmount>13960</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>13960</PatientPayAmount>
      </SubTotalValues>
      <Message>
        <Type>W</Type>
        <Code>3002</Code>
        <Description>CLAIM UNDER REVIEW</Description>
      </Message>
      <TotalValues>
        <GrossAmount>13960</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>13960</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
    <ServiceResponse>
      <Number>9</Number>
      <BenefitCode>UNK</BenefitCode>
      <Identifier>2364</Identifier>
      <SubTotalValues>
        <GrossAmount>4640</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>4640</PatientPayAmount>
      </SubTotalValues>
      <Message>
        <Type>W</Type>
        <Code>3002</Code>
        <Description>CLAIM UNDER REVIEW</Description>
      </Message>
      <TotalValues>
        <GrossAmount>4640</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>4640</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
    <ServiceResponse>
      <Number>10</Number>
      <BenefitCode>UNK</BenefitCode>
      <Identifier>2361</Identifier>
      <SubTotalValues>
        <GrossAmount>800</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>800</PatientPayAmount>
      </SubTotalValues>
      <Message>
        <Type>W</Type>
        <Code>3002</Code>
        <Description>CLAIM UNDER REVIEW</Description>
      </Message>
      <TotalValues>
        <GrossAmount>800</GrossAmount>
        <NettAmount>0</NettAmount>
        <LevyAmount>0</LevyAmount>
        <PatientPayAmount>800</PatientPayAmount>
      </TotalValues>
    </ServiceResponse>
  </Response>
</Claim>
    `

    const x = new JSONProcessor()

    const z = await x.ClaimProcessor(data)
    return this.claim.GetClaimResponse(z)
  }
}
